[book]
authors = ["sitandr"]
language = "en"
multilingual = false
src = "src"
title = "Typst Examples Book"

[preprocessor.typst-highlight]
#disable_inline = true
typst_default = true
render = true
warn_not_specified = true

[output.html]
additional-css = ["./theme/mdbook-pagetoc/style.css"]
additional-js = ["./theme/mdbook-pagetoc/sidebar.js"]

[output.html.redirect]
"/snippets/hidding.html" = "./hiding.html"
